name: Haxelib

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: markdown-openfl-textfield-haxelib
          path: |
            src/
            haxelib.json
            README.md
            LICENSE
          if-no-files-found: error
